[build]
  publish = "."

[[headers]]
  for = "/*.ipynb"
  [headers.values]
    Content-Type = "application/x-ipynb+json"
    Content-Disposition = "attachment"

[[headers]]
  for = "/**/*.ipynb"
  [headers.values]
    Content-Type = "application/x-ipynb+json"
    Content-Disposition = "attachment"
